"""empty message

Revision ID: 0353779ec628
Revises: 710ef1086797
Create Date: 2022-03-21 18:11:50.543187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0353779ec628'
down_revision = '710ef1086797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'language', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='unique')
    # ### end Alembic commands ###
