"""empty message

Revision ID: 3f0435ca917e
Revises: 4eade25fc169
Create Date: 2022-03-21 18:14:39.800368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0435ca917e'
down_revision = '4eade25fc169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'language', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='unique')
    # ### end Alembic commands ###
