"""empty message

Revision ID: 93f5b3e116f6
Revises: 3f0435ca917e
Create Date: 2022-03-21 18:18:59.761066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f5b3e116f6'
down_revision = '3f0435ca917e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workspace_role', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_role', type_='unique')
    # ### end Alembic commands ###
