"""empty message

Revision ID: 9ff2a7b0e42a
Revises: f638446bf66d
Create Date: 2022-03-21 12:06:24.456040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff2a7b0e42a'
down_revision = 'f638446bf66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'api_key')
    # ### end Alembic commands ###
